@ECHO OFF
@IF EXIST A:\CONFIG.QDK COPY A:\CONFIG.QDK A:\CONFIG.SYS >NUL:
@IF EXIST A:\AUTOEXEC.QDK COPY A:\AUTOEXEC.QDK A:\AUTOEXEC.BAT >NUL:
@IF EXIST C:\QEMM\DOS-UP.QDK COPY C:\QEMM\DOS-UP.QDK C:\QEMM\DOS-UP.DAT >NUL:
@IF EXIST C:\QEMM\LOADHIRF.QDK COPY C:\QEMM\LOADHIRF.QDK C:\QEMM\LOADHI.RF >NUL:
@IF EXIST C:\QEMM\OPT??.BAT DEL C:\QEMM\OPT??.BAT >NUL:
